import type { CapacitorConfig } from '@capacitor/cli';

/**
 * Pushkaralu native shell — Capacitor configuration.
 *
 * Why these choices:
 *  - `webDir: 'www'`            — bundled static portal lives there. www/ is
 *                                  generated by `npm run sync:web` from
 *                                  ../dashboards/, so the website remains the
 *                                  single source of truth.
 *  - `androidScheme: 'https'`   — required for the existing service worker
 *                                  (sw.js) to register inside the WebView.
 *                                  Without this, Capacitor uses
 *                                  `capacitor://localhost` which blocks SW.
 *  - `allowNavigation`          — whitelists the live backend, OSM tiles,
 *                                  Google Fonts and Leaflet CDN so the
 *                                  bundled HTML loads exactly the resources
 *                                  the web version does.
 *  - Plugin configs             — sensible defaults for splash screen,
 *                                  status bar, geolocation accuracy, push.
 */
const config: CapacitorConfig = {
  appId: 'in.gov.ap.pushkaralu',
  appName: 'Pushkaralu',
  webDir: 'www',
  // `bundledWebRuntime` was removed in Capacitor 6 — including it makes
  // the CLI reject the config when it parses TypeScript, so we omit it.

  server: {
    androidScheme: 'https',
    iosScheme: 'https',
    // Resources loaded by user.html that are NOT in the bundle:
    //   - pushkara.onrender.com         API + WebSocket backend
    //   - *.tile.openstreetmap.org      Map tiles
    //   - cdnjs.cloudflare.com          Leaflet
    //   - fonts.googleapis.com / gstatic.com
    //   - unpkg.com                     Leaflet (alt CDN)
    allowNavigation: [
      'pushkara.onrender.com',
      '*.pushkara.onrender.com',
      '*.tile.openstreetmap.org',
      'tile.openstreetmap.org',
      'cdnjs.cloudflare.com',
      'unpkg.com',
      'fonts.googleapis.com',
      'fonts.gstatic.com',
    ],
  },

  android: {
    allowMixedContent: false,
    captureInput: true,
    webContentsDebuggingEnabled: true,
    // Adjust resize so soft keyboard doesn't push toolbar offscreen
    backgroundColor: '#0B2E6E',
  },

  ios: {
    contentInset: 'always',
    backgroundColor: '#0B2E6E',
    limitsNavigationsToAppBoundDomains: false,
  },

  plugins: {
    SplashScreen: {
      launchShowDuration: 1500,
      launchAutoHide: true,
      launchFadeOutDuration: 300,
      backgroundColor: '#0B2E6E',
      androidSplashResourceName: 'splash',
      androidScaleType: 'CENTER_CROP',
      showSpinner: false,
      splashFullScreen: true,
      splashImmersive: false,
    },
    StatusBar: {
      style: 'LIGHT',
      backgroundColor: '#0B2E6E',
      overlaysWebView: false,
    },
    PushNotifications: {
      presentationOptions: ['badge', 'sound', 'alert'],
    },
    Geolocation: {
      // permissions are requested at runtime by capacitor-bridge.js
    },
    LocalNotifications: {
      smallIcon: 'ic_stat_icon_config_sample',
      iconColor: '#0B2E6E',
      sound: 'default',
    },
    CapacitorHttp: {
      // Disabled: existing user.html uses fetch() which works natively over HTTPS
      enabled: false,
    },
  },
};

export default config;
